[theme]
inherit = "none"
stylesheets = [
    "assets/style/theme.css",
]
sidebars = [
    "localtoc.html",
    "relations.html",
    "sourcelink.html",
    "searchbox.html",
]
pygments_style = { default = "style_name", dark = "dark_style" }

[options]
